- LICENSE
Add an explicit MIT License file.
> Added an MIT license file.

- lib/event_broker.js
- lib/peer_socket.js
- test/test_virtual_device.js
> Virtual device event bug

- lib/virtual_device.js
- test/test_virtual_device.js
> virtual device implements createReadStream()

- .travis.yml
- package.json
- test/test_consumer_stream.js
> Updating Argo to the latest version.

- lib/api_formats/siren/device.siren.js
- lib/api_formats/siren/devices.siren.js
- lib/api_formats/siren/server.siren.js
- test/test_api.js
Small api improvements, fixes #175 and #174
> Api updates

- README.md
Should fix the formatting issue on npm readme. https://www.npmjs.com/package/zetta
> Updated readme to format better in npm

- lib/api_resources/root.js
- test/test_peer_connection_api.js
> Relation update

- lib/api_resources/root.js
- lib/api_resources/servers.js
- lib/registry.js
- test/test_query_api.js
> Adding error reporting for invalid queries sent via the API.

- lib/api_resources/root.js
- lib/http_server.js
- test/test_query_api.js
> Updates to query API.

- lib/api_formats/siren/device.siren.js
- lib/api_formats/siren/devices.siren.js
- lib/api_formats/siren/metadata.siren.js
- lib/api_formats/siren/server.siren.js
- lib/api_formats/siren/type.siren.js
- lib/api_resources/servers.js
- package.json
- test/test_api.js
- test/test_metadata_api.js
- test/test_query_api.js
This adds device metadata to the API.
> Device Metadata

- lib/registry.js
- test/test_zetta.js
Still working on a way to test this.
> Removed try/catch around callbacks

- lib/api_formats/siren/device.siren.js
- lib/api_formats/siren/devices.siren.js
- lib/api_formats/siren/server.siren.js
- lib/api_resources/servers.js
- package.json
- test/test_api.js
- test/test_event_ws_connection.js
Stubbed out server update via API.  Implemented device update via API.
Not ready for merge.
> Support runtime updates of device properties via the API.

- lib/api_resources/peer_management.js
- lib/peer_client.js
- lib/peer_socket.js
- test/test_virtual_device.js
Everything working now.
- This PR also fixes an issue in the PeerClient that was found while testing, calling stop() on PeerClient previously did not stop the client from reconnecting. Talking with @mdobson this was the intended behavior.
> Cleanup spdy streams to fix memory issue

- lib/runtime.js
- test/test_remote_query.js
> Fix for remote queries targeting specifc servers.

- lib/http_server.js
- test/test_api.js
> Catching error events from proxyToPeer(s) with test.

- lib/api_formats/siren/device.siren.js
- package.json
- test/test_api.js
- test/test_driver.js
Expose and hide streams in API via device drivers. Another feature of device presence.
> Enabled streams should be published in the API, disabled streams should be hidden.

- lib/event_socket.js
- test/test_event_ws_connection.js
Fixing an issue where _peer/connect and _peer/disconnect notifications on the peer-management streams where coming back malformed.
> Peer streams

- lib/event_broker.js
- lib/event_socket.js
- package.json
- test/test_event_broker.js
- test/test_event_streams.js
- test/test_event_ws_connection.js
- test/test_remote_query.js
- test/test_stream_topic.js
Fixes issues #251 #252.
Work in progress till we get https://github.com/zettajs/zetta-events-stream-protocol/pull/1 merged in.
> Events stream issues

- lib/pubsub_service.js
- test/test_event_streams.js
> Fixed issue with circular buffer in _peer/connect events when sending to a peer

- lib/event_broker.js
- test/test_event_streams.js
> EventBroker now unsubscribing from _peer/connect when topic is unsubscribed from.

- package.json
- test/test_event_streams.js
- test/test_stream_topic.js
Tests for streamtopic issue. Waiting on this PR https://github.com/zettajs/zetta-events-stream-protocol/pull/3.
Fixes #251
> Added tests for stream topic edge cases

- lib/http_server.js
- test/fixture/example_driver.js
- test/test_api.js
> Fixed how we were str joining the buffer for the proxied request body.

- lib/api_resources/servers.js
- test/test_api.js
> Decode hub names correctly when spaces are present.

- lib/event_socket.js
- package.json
- test/test_event_stream_parser.js
- test/test_event_streams.js
Fixes second part of #280, returning 405 properly.
Needs https://github.com/zettajs/zetta-events-stream-protocol/pull/4 before tests will pass.
> Multiplexed ws protocol errors

- lib/api_resources/servers.js
- test/test_query_api.js
> Server queries: handle case with no devices provisioned

- README.md
Fixes markdown issue with npm and Gitter badge.
> Fix Gitter in README

- package.json
> Updates to package.json to fix repo, description, and add better keywords
