zettajs/zetta

zetta.js

Fixes issue with LockFile in medea from init being called twice.

Initialize medea files before adding scouts/devices

---

lib/api_resources/peer_management.js
lib/event_broker.js
lib/event_socket.js
lib/http_server.js
lib/peer_client.js
lib/peer_socket.js
test/test_event_socket.js
test/test_event_ws_connection.js

Allows connecting to `wscat -c http://localhost:5000/peer-management` (cloud) and getting messages like:
```
< {"topic":"_peer/disconnect","timestamp":1422563336669,"data":{"id":"detroit","connectionId":"9d6c596b-c25d-48d7-9791-5651f811d72a"}}
< {"topic":"_peer/connect","timestamp":1422563337670,"data":{"id":"detroit","connectionId":"fa36b150-7fc6-4f10-8f41-6129113dc6f8"}}
< {"topic":"_peer/disconnect","timestamp":1422563338089,"data":{"id":"detroit","connectionId":"fa36b150-7fc6-4f10-8f41-6129113dc6f8"}}
```
Or from the hub side:  `wscat -c ws://localhost:5002/peer-management`
```
connected (press CTRL+C to quit)
< {"topic":"_peer/disconnect","timestamp":1422563409746,"data":{"url":"ws://localhost:5000/peers/detroit","connectionId":"356c1a66-e5e2-4b9d-91c1-7c2bf73f357b"}}
< …
```

Peering event stream

---

zetta_runtime.js

This helps with allowing to create things like we do in `test/fixture/mem_registry.js` when running outside the zetta repo.
ex:
```js
var util = require('util');
var levelup = require('levelup');
var memdown = require('memdown');
var DeviceRegistry = require('../../lib/device_registry');
var MemRegistry = module.exports = function() {
var db = levelup({ db: memdown });
DeviceRegistry.call(this, { db: db, collection: 'devices' });
}
util.inherits(MemRegistry, DeviceRegistry);
```

zetta package exposes device registry and peer registry files

---

lib/peer_socket.js
test/test_peer_connection.js

Handle peer's spdy agent error event

---

package.json
test/test_zetta.js
zetta.js

This PR will fail until https://github.com/zettajs/zetta-auto-scout/pull/4 is merged in and pushed to `npm`.

Includes a hack to allow .use(Device) to only call .init once on the device

---

zetta.js

var uuid = require('node-uuid');
var Device = require('zetta-device');
var HttpDevice = require('zetta-http-device');
var Scout = require('zetta-scout');
Above modules removed from zetta.js file since none of them are really used in zetta.js file.

Removed unused modules from zetta.js file

---

lib/peer_socket.js

Previously peers were getting stuck in the api in certain cases. Fixes #156

Properly emitting error on peer timeouts.

---

test/test_zetta.js
zetta.js

Accounting for adding extra arguments to an app. This use case now works.
```
var app = function(server, foo, bar) {}
var z = require('zetta');
z()
.use(app, 1, 2)
.listen(0);
```

Updated use to incorporate additonal arguments for an app.

---

lib/http_server.js
test/test_peer_connection.js

There is a bug in the peer connection where if a peer_socket emits an `error` or `end` event multiple times per one `connected` event it causes an issue with http_server managing the connected peers.
Only way i was able to get the peer_socket to emit multiple `error` events was to have a peer connect to my laptop then disconnect the wifi. There will be an `error` event emitted from the ping timer code that says its connection timed out. But there is another event being thrown from somewhere else.

Fix peer event subscriptions

---

lib/http_server.js
lib/peer_socket.js
lib/runtime.js
test/test_peer_connection.js

- Changes the internals of http_server and peer_socket to remove http_server from having to keep track of a list of connected vs disconnected peers. It was causing an issue when a peer disconnects before the peer connection was fully established then next time the peer connected it would not re-subscribe to any event topics.

Peer socket connection issue

---

lib/api_resources/root.js
lib/event_broker.js
lib/http_server.js
lib/query_topic.js
test/test_query_api.js
test/test_remote_query.js

Fixes #176.
Fixing URL in root-level search results self link.
Adding some more protection around body parsing for root level queries.
Returning local results in addition to peer results when querying across servers.
Wiring up reactive WebSocket for cross-server queries.
Subscribing to new peers on cross-server query.
Fixing issue with duplicate events.
Adding another check for cross-server query test.
Cleaning up observable after query subscription is removed.
Removing stray console.log
Reverting ID change to name on cross-server query clients.

Cross-server query support.

---

lib/api_formats/siren/metadata.siren.js
lib/api_formats/siren/server.siren.js
test/test_api.js
test/test_zetta.js
zetta.js

Implements #154 
```js
zetta()
.name('somename')
.properties({ custom: 123 })
.listen(0);
```
API response in `GET /servers/somename` will have properties set to `{ name: 'somename', custom: 123 }`.
You can fetch current properties with name as well using `.getProperties()`

Added custom properties to server.

---

lib/runtime.js
test/test_remote_query.js

Example:
```js
module.exports = function(server) {
var query = server.from('*').where({ type: 'led' });
server.observe(query, function(device) {
console.log('found led', device.id)
});
};
```

Added support to query .from('*') in zetta app.

---

lib/api_formats/siren/device.siren.js
lib/api_formats/siren/server.siren.js
lib/http_server.js
test/test_api.js

This change adds a check to see if the request is being forwarded from one Zetta server to another using HTTP or HTTPS.  If so, it sets headers accordingly and makes sure event link URLs come back with ws(s):// schemes.  If the connection is SPDY, it will use http(s):// schemes for events.  Tests included.

Fix for #202

---

lib/http_server.js
test/test_event_ws_connection.js

WIP branch for now. We have to do funky stuff to allow folks to extend zetta via websockets. Here is what the changes entail. This aims to fix #208.
1. We removed the web socket server setup from the `init()` function on `lib/http_server.js` and put it in the constructor.
2. We updated the web socket server to have us manually handle upgrades through it via the `noServer` flag
3. On the `upgrade` event from the http / spdy server we parse the URL to check if it's one of the following
* `/peers`
* `/peer-management`
* `/servers/serverId/events`
* `/events`
4. If it is one of those reserved urls we then pass the handle event arguments to the web socket server, and create the connection.
5. We then handle the web socket as we would normally in the old code.
We had to do this because:
1. The …

Allowing zetta users to extend websocket model with server extensions.

---

lib/api_resources/servers.js
package.json
test/test_driver.js

Needs https://github.com/zettajs/zetta-device/pull/11 and https://github.com/zettajs/zetta-scientist/pull/2 to be merged first.
Device API and Z2Z - Returns the default remoteFetch method of the user supplied one. Then appends name, id, state, and type to that object. This is done using the device's `.properties()` method.
Device Update API - Uses the device's `_remoteUpdateHandler` method to update properties on the device. If device is using old version of zetta-device that does not support updates API returns a 501.
Zetts-device handles this by first filtering all reserved keys out, then calls the default remoteUpdate method or the user supplied one. Then triggers the zetta-properties-update transition. The default remoteUpdate filters all monitor values out and deletes any key the …

Hooks for remoteUpdate and remoteFetch

---

lib/api_resources/servers.js
lib/runtime.js
test/test_runtime.js

- Trying to emit to `this.log` when it should be `this._log`
- Callback not called on `_destroyDevice()` if device isn't compatible with new delete functionality.

Fixing two bugs in the runtime.

---

lib/api_resources/peer_management.js
lib/peer_client.js
test/test_peer_connection_api.js
zetta.js

- Removes unsupported websocket link for each peer. Fixes #233
- PUT method now updates the internal peer instead of creating a new peer connection. Fixes #236
- Actions only show on peer entity when it's either an `initiator` or when the status is `connected`. Fixes: #210

Peer management updates

---

lib/api_resources/servers.js
test/fixture/example_driver.js
test/test_api.js
test/test_virtual_device.js

Currently only parsing `number` and `date` input types to their native counterpart in JS. All other listed in Siren spec don't have native type in JS.
`hidden`, `text`, `search`, `tel`, `url`, `email`, `password`, `datetime`, `date`,
`month`, `week`, `time`, `datetime-local`, 
`number`, `range`, `color`, `checkbox`,
`radio`, `file` 
Question: if the input arg parses to a `NaN` or not a date should we return a 400. Currently it's not, those are passed to the driver. @mdobson @kevinswiber

Decoding transition args to number/string/date based on input type in driver

---

lib/api_resources/devices.js
lib/api_resources/root.js
lib/api_resources/servers.js
lib/http_server.js
lib/peer_socket.js
lib/pubsub_service.js

**Note: These changes are not backwards-compatible.  All previous versions will need to be upgraded.**
* Remove zetta-forwarded-server header:  This information can be parsed out of the request URL.
* Remove zetta-message-id header: This information can be obtained by passing around response references.
* Change X-Event-Encoding header to Content-Type: Instead of using `json` and `buffer` as the values, favor `application/json` and `application/octet-stream`.
* Change Host header from `fog.argo.cx` to `{{server-id}}.unreachable.zettajs.io`.

Zetta-to-Zetta Protocol Changes

---

lib/virtual_device.js
test/test_virtual_device.js

Only throw an error in the default VirtualDevice callback if an error has been provided.  Fixes #240.

---

test/test_event_ws_connection.js
test/test_peer_connection.js

Fixes an issue with subscribe's callback to peer events being fired multiple times during the test suite. Most of the time the second call was a result of a peer timing out or reconnecting and firing a second _peer/disconnect.
This fixes only two problem test cases. Anytime we call pubsub.subscribe on '_peer/connect' and `_peer/disconnect` we may have similar issues.
Would be helpful for the tests and zetta in general if we had a pubsub.once() method. Then we wouldn't have to manually unsubscribe to these events in the tests.

Fixed a test that was causing issues, especially in node@0.10

---

lib/peer_client.js

If no pings are seen coming from the cloud after 30sec disconnect ws and reconnect. Monkey patch is kinda shitty but I couldn't find another way with how spdy doesn't expose the abstract connection that emits ping. Still gotta at some tests.
What's your thoughts on this approach? @mdobson @kevinswiber

Added watchdog for ping going into the peer_client.

---

lib/event_broker.js
lib/event_socket.js
lib/http_server.js
lib/peer_socket.js
lib/pubsub_service.js
package.json
test/test_event_broker.js
test/test_event_streams.js
test/test_pubsub.js

- handles event stream topic edge cases that have an ambiguous pubsub topic.
- Pubsub and EventBroker only publish a unique message to their clients once. This broke b/c of how we are now using wildcards and regexes in the topics. Two topics can fulfill the same unique message. We only want a) the message to go to a peer once, b) clients to only receive the message once per subscriptionId.
Incorporates a refactor of the EventBroker.
- Peer now always pushes events to cloud with the topic of the event not the subscription topic.
- Peer_sockt emits "zetta-events" on any push data from peer.
- HttpServer listens for "zetta-events" and publishes it to local pubsub with the format <serverName>/<topic>
- EventBroker now listens on local pubsub for both local and remote events.
- Skipping …

Websocket stream topic issues

---

lib/http_server.js
test/test_event_ws_connection.js

http_server will wait 5 seconds to see if bytesWritten has gone up for any sockets that are not handled by zetta if bytesWritten is 0 after 5 seconds send 404. It also sends 404 immediately if there is only one listener on the `upgrade` event for the http server.

Send 404 on ws that are not handled by zetta or an extension

---

lib/http_server.js

This updates the `proxyToPeer` code in `http_server.js` to pipe the response body back to the client unless specifically told not to by `env.proxyOpts` which is only used for cross server device queries.
Also removes the need to keep the res in `httpServer.clients` I think this was leftover from some earlier code but unnecessary when we have the `env.response` object in scope.

When proxying requests to a hub use piping unless told not to.

---

lib/event_socket.js
test/test_event_streams.js

Adds support for ping/pong (#280)  as proposed in https://docs.google.com/document/d/1-vkl6o5PjdgsPACXEo80-sF9gPkK9JNIGKxZ8G-2rtM/edit# needs https://github.com/zettajs/zetta-events-stream-protocol/pull/5 to be merged in first.

Multiplexed ws: Added support for proposed ping/pong message types.

---

lib/http_server.js
lib/virtual_device.js
test/test_virtual_device.js

VirtualDevice properly formats Actions before updating state

---

lib/virtual_device.js
test/test_virtual_device.js

Implements the `available()` on VirtualDevice to match methods exposed on Device. Fixes #278 
`.available()` returns state based on what the cloud thinks the state of the device is on a hub getting info from logs topic stream and the return from a transition call. There could be times where the state does not line up.

VirtualDevice expose .available()

---

lib/web_socket.js

Will show a message similar to below when peering fails with non 101 status code.
```
Apr-19-2016 14:49:04 [peer-client] Peer connection error (ws://google.com/peers/milford-1): server returned 404
```

Show better error message when peering fails.

---

package.json

PR to merge in the code moves the device_config.js to the `zetta-device` package. Because of how our deps work there is a number of PRs needed before this can be merged.
All changes are backwards compatible with the scientist throwing a deprecation warning if the Device driver is using a zetta-device version < 0.19.0.
- https://github.com/zettajs/zetta-scientist/pull/6
- https://github.com/zettajs/zetta-device/pull/20
- https://github.com/zettajs/zetta-scout/pull/7
- https://github.com/zettajs/zetta-auto-scout/pull/9
Fixes #290

Using latest zetta-device deps.

---

test/test_api.js

Beta 6 release did not update the host values in siren responses to
match the value provided by "x-forwarded-host" header. This PR adds
a unit test to verify correct host values.

Unit Test for "x-forwarded-host" Header

---

lib/http_server.js
test/test_zetta.js

Implements #314
```js
.use(function() {
// Peer connection
server.httpServer.onPeerConnect(function(request, socket, head, next) {
// Handle auth logic, 
next(); // Continue the peering process
// or
next(new Error('Some error')); // Response to peer will be 500
})
// Regular data websocket connections
server.httpServer.onEventWebsocketConnect(function(request, socket, head, next) {
// Handle auth logic, 
next(); // Continue the event_socket process
// or
next(new Error('Some error')); // Response to client will be 500
})
})
```
It also allows for multiple hooks for each event by calling the method more than once. In that case each hook is called in series.

Peer connect and event websocket connection hooks.

---

lib/event_socket.js
lib/peer_client.js
test/test_peer_client.js
zetta.js

Incorporates changes from #312 and includes tests.
`_peer/disconnect` message will container `error` property if PeerClient disconnected with an error. This will also be persisted in the peer registry.

Emit and Publish Peer Connection Errors

---

lib/event_broker.js
lib/event_socket.js
lib/http_server.js
test/test_event_socket.js
test/test_event_streams.js

Adds `filterMultiple` query parameter to multiplexed ws. If `filterMultiple` is set as a query parameter on `WS /events` then all events that fulfill multiple subscriptions will only be sent once to the client. The `subscriptionId` will always be an array of subscriptions it fulfills.
Eg.
Without `filterMultiple` subscribing to `**` and `*/photocell/*/intensity`
```
λ: wsta ws://localhost:1337/events '{"type": "subscribe", "topic": "**"}' '{"type": "subscribe", "topic": "*/photocell/*/intensity"}'
Connected to ws://localhost:1337/events
{"type":"subscribe-ack","timestamp":1467138805442,"topic":"**","subscriptionId":1}
{"type":"subscribe-ack","timestamp":1467138805442,"topic":"*/photocell/*/intensity","subscriptionId":2}
{"type":"event","topic":"milford/photocell/e7ffb5e3-6961-4d03-8eca-e42 …
```

Multiplex ws allow duplicate messages to be filtered

---

lib/http_server.js
test/test_api.js
zetta.js

_zetta.js_ : updated to include `useXForwardedRootHeader` option when
creating `HttpServer` instance.
_lib/http_server.js_ : updated to include `useXForwardedRootHeader`
option as part of call to `titan`
_test/test_api.js_ : updated with new tests that include the new
"X-Forwarded-Root" header as well as more tests for the existing
"X-Forwarded-Host" header. Main additions are to parse `href` values
in the response body to check expected host or root path value.
---
PR depends on argo/titan#5 and argo/argo-url-helper#4

Add Support & Tests for X-Forwarded-Path

---

lib/api_resources/servers.js
package.json
test/fixture/example_driver.js
test/test_api.js

We have a couple of cases where we need to know **why** an action failed.  We could come up with some work around with the server log or monitored properties, but that is not an ideal way to handle errors. 
This is written such that existing callbacks will not be affected.  The `err` object must have a "properties" member for the behavior to be triggered.  I also added a test case to validate the Siren response.

Custom responses for failed actions

---

lib/http_server.js
lib/peer_socket.js
test/test_zetta.js

Can modify PeerSocket timeout options using.
```js
zetta()
.use(function(server) {
server.httpServer.peerOptions = {
pingTimeout: 25000, // 25s
confirmationTimeout: 2000 //2s
};
});
```

Added optional PeerSocket options to set timeouts

---

lib/http_server.js

Tried it on my windows machine and it works like a charme now!

Fixed replacement for windows URLs, issue #331

---

lib/event_broker.js

The call to `EventBroker.prototype.client` checks the given `client`
instance for `streamEnabled`. If "true", the client is passed to
`_streamEnabledClient` where it has "close" and "unsubscribe" event
handlers added. If the client is *not* `streamEnabled` the event
handlers are *not* added.
This means that the `_subscribe` method only needs to make sure to
call unsubscribe on the "close" event of clients that are not
`streamEnabled`.
---
This PR is to address Issue #351

Stream Enabled Clients Do Not Need Close Handler

---

package.json

No breaking changes.
It might be a good idea to prefer explicit over implicit though (`colors.green('hello')` instead of `'hello'.green`). I guess this is a matter of taste, but extending prototype does not sound clean to me.

:arrow_up: Update colors dependency

---

.npmignore

From around 600KB to 147KB
```
npm notice
npm notice 📦  zetta@1.5.1
npm notice === Tarball Contents ===
npm notice 1.6kB  package.json
npm notice 1.1kB  LICENSE
npm notice 2.3kB  README.md
npm notice 364B   zetta_runtime.js
npm notice 11.5kB zetta.js
npm notice 2.6kB  lib/api_formats/siren/device.siren.js
npm notice 1.0kB  lib/api_formats/siren/devices.siren.js
npm notice 1.1kB  lib/api_formats/siren/metadata.siren.js
npm notice 2.3kB  lib/api_formats/siren/server.siren.js
npm notice 733B   lib/api_formats/siren/type.siren.js
npm notice 820B   lib/api_resources/devices.js
npm notice 10.3kB lib/api_resources/peer_management.js
npm notice 9.6kB  lib/api_resources/root.js
npm notice 14.6kB lib/api_resources/servers.js
npm notice 554B   lib/device_registry.js
npm notice 11.3kB …
```

Added npmignore to cut down on package size.
